<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ADMINRG-8TM2G52" name="Test" tests="4" failures="1" timestamp="27 Aug 2021 19:09:42 GMT" time="59.551" errors="0">
  <testcase name="@AfterMethod captureFailedTestCase" time="0.0" classname="com.qa.test.loginTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.qa.utilPackage.captureScreenShots.screenShot(captureScreenShots.java:19)
	at com.qa.test.loginTest.captureFailedTestCase(loginTest.java:40)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod captureFailedTestCase -->
  <testcase name="@AfterClass kill" time="0.0" classname="com.qa.test.loginTest">
    <skipped/>
  </testcase> <!-- @AfterClass kill -->
  <testcase name="runTest" time="10.331" classname="com.qa.test.ADDcustomerTestclass"/>
  <testcase name="validateTitle" time="0.002" classname="com.qa.test.loginTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.qa.test.loginTest.validateTitle(loginTest.java:31)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- validateTitle -->
  <testcase name="RememberMeTextValidation" time="0.244" classname="com.qa.test.uiTestforLoginPage"/>
  <testcase name="validateWelcomeText" time="0.319" classname="com.qa.test.uiTestforLoginPage"/>
</testsuite> <!-- Test -->
